### ISSUE TITLE
谢谢前辈的辛苦，请问可以用来做分布式爬虫用吗

### ISSUE THREAD

**Issue by iloveyo123u1** [everydo/ztq#9]
你好 前辈  我想做一个分布式爬虫
需要用一个东西来做任务管理 调度什么的

由于我是新手  所以不是很懂

我现在只会写 单机的爬虫
http://python-china.org/topic/765
这是我在python -china的提问， 谢谢前辈

**Comment by panjunyong** [comment]
我没做过爬虫，这部分需求，不是很清楚。

现在ztq的底层还不是采用协程，所以效率不是很高。但是让某些任务已协程方式运行应该也是可以的。
